# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-29 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name="College's name")),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name="Student's name")),
                ('age', models.IntegerField(verbose_name="Student's age")),
                ('is_graduated', models.BooleanField(default=False, verbose_name='Graduated')),
                ('birthday', models.DateTimeField(verbose_name='Birthday')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.College', verbose_name="Students's college")),
            ],
        ),
    ]
